name: picklebay-cms dev CI

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: dev-runner

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: |
          touch .env
          echo "$${{ secrets.DEV_ENV_FILE }}" > .env
      - run: npm run build
      - run: pm2 restart picklebay-cms-vite
      - run: pm2 flush picklebay-cms-vite
